swagger: "2.0"
info:
  title: Settings Microservice
  description: Settings Microservice aids managing configurations
  version: 1.0.0

basePath: /v1/
consumes:
  - application/json
produces:
  - application/json


paths:
  /placeholder_DOES_NOT_DO_ANYTHING_REMOVE_AFTER_ADDING_OTHER_ROUTES:
    get:
      tags: ["Placeholder"]
      summary: "Redirect"
      description: "Redirect user to swagger ui"
      operationId: settings.placeholder.get
      responses:
        "302":
          description: "Found"

#definitions:

